# Generated by Django 4.2.17 on 2025-02-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantitu",
            new_name="quantity",
        ),
    ]
